services:
  musicnotegame:
    container_name: musicnotegame
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/var/www/musicnotegame
      - ./mysql:/var/lib/mysql
    ports:
      - "80:80"
      - "9006:3306"
    networks:
      - default

